# Relevant file/directory paths
PATHS:
  RAW_DATA_DIR: 'data/raw/quarterly/'
  RAW_DATASET: 'data/raw/intermediate/raw_data.csv'
  RAW_EXOG_DATASET: 'data/raw/intermediate/all/raw_exog_data.csv'
  FULL_RAW_DATASET: 'data/raw/full_raw_data.csv'
  PREPROCESSED_DATA: 'data/preprocessed/all/preprocessed.csv'
  PREPROCESSED_DWT_DATA: 'data/preprocessed/dwt/preprocessed.csv'
  PREPROCESSED_CEEMDAN_DATA: 'data/preprocessed/ceemdan/preprocessed.csv'
  CLIENT_DATA: 'data/preprocessed/client_data.csv'
  CAT_FEAT_MAP: 'data/serializations/cat_feat_map.yml'
  MODELS: 'results/models/'
  DATA_VISUALIZATIONS: 'img/data_visualizations/'
  FORECAST_VISUALIZATIONS: 'img/forecast_visualizations/'
  EXPERIMENT_VISUALIZATIONS: 'img/experiment_visualizations/'
  INTERPRETABILITY_VISUALIZATIONS: 'img/interpretability_visualizations/'
  LOGS: 'results\\logs\\'
  EXPERIMENTS: 'results/experiments/'
  TRAIN_SET: 'data/preprocessed/Train_Set.csv'
  TEST_SET: 'data/preprocessed/Test_Set.csv'
  SCALER_COL_TRANSFORMER: 'data/serializations/scaler_col_transformer.bin'
  ORDINAL_COL_TRANSFORMER: 'data/serializations/ordinal_col_transformer.bin'
  OHE_COL_TRANSFORMER: 'data/serializations/ohe_transformer_sv.bin'
  PREDICTIONS: './results/predictions/'
  INTERPRETABILITY: './results/interpretability/'
  K-PROTOTYPES_CENTROIDS: 'results/experiments/cluster_centroids_'
  K-PROTOTYPES_CLUSTERS: 'results/experiments/client_clusters_'
  IMAGES: './img/visualizations/'
  SERIALIZATIONS: './data/serializations/'

# important dates for forecasting
DATES:
  HOLIDAYS:
      Official Holiday: ["2021-01-01","2021-01-06","2021-04-04","2021-04-05","2021-04-25","2021-05-01",
                          "2021-06-02","2021-08-15","2021-11-01","2021-12-05","2021-12-25","2021-12-26",
                          "2022-01-01","2022-01-06","2022-04-17","2022-04-18","2022-04-25","2022-05-01",
                          "2022-06-22","2022-08-15","2022-11-01","2022-12-08","2022-12-25","2022-12-26"]
      Event Day:        ["2021-03-28","2021-05-09","2021-10-31","2021-11-28","2021-05-12","2021-12-12",
                          "2021-12-19","2021-12-31","2022-03-27","2022-04-10","2022-05-08","2022-05-09",
                          "2022-10-30","2022-11-27","2022-12-04","2022-12-11","2022-12-18","2022-12-31"]
      Unofficial Holiday: ["2021-04-23","2021-05-23","2022-04-23","2022-06-05"]

# Constants describing data
DATA:
  FREQUENCY: ['H']
  PREPROCESS: ['IMPUTE', 'CEEMDAN', 'DWT', 'ANOMOLY_REMOVAL']  # One of ['IMPUTE', 'CEEMDAN', 'DWT', 'ANOMOLY_REMOVAL']
  CEEMDAN_DECOMPOSITIONS: 5 # None
  DWT_DECOMPOSITIONS: 1 # None
  WEATHER_FEATS: []  # One of ['AIR_TEMP', 'AIR_HUMIDITY', WIND_SPEED', RAIN_DEPTH']
  TIME_FEATS: ['WEEKEND', 'HOUR', 'HOLIDAY']  # One of ['WEEKEND', 'HOUR', 'HOLIDAY']
  SPECIFIC_FEATS: ['DIURNAL', 'K_MEANS']  # One of ['DIURNAL', 'K_MEANS']
  TEST_FRAC: 0.25
  TEST_DAYS: 672
  TRAIN_DAYS: 168
  START_TRIM: 11000
  END_TRIM: 168
  DMAS: ['dma_b']
  MISSING_RANGES: []
  SAVE_LABEL: ANN_DWT

# Training experiments
TRAIN:
  MODEL: 'ann'                      # One of ['prophet', 'lstm', 'gru', '1dcnn', 'arima', 'sarimax', 'random_forest', 'linear_regression']
  DECOMPOSITION: ['DWT']                 # One of ['CEEMDAN', 'DWT'] 
  EXPERIMENT: 'hparam_search'        # One of ['train_single', 'train_all', 'hparam_search', 'cross_validation']   
  N_QUANTILES: 34
  N_FOLDS: 7
  HPARAM_SEARCH:
    N_EVALS: 30
    HPARAM_OBJECTIVE: 'MSE'             # One of ['MAPE', 'MAE', 'MSE', 'RMSE']
    LAST_FOLDS: 4
  INTERPRETABILITY: true

# Forecasting
FORECAST:
  MODEL: 'ann'                      # One of ['prophet', 'lstm', 'gru', '1dcnn', 'arima', 'sarimax', 'random_forest', 'linear_regression']
  MODEL_PATH: './results/models/ARIMA20240411-125159.pkl'
  DAYS: 168

# Hyperparameters specific to individual models
HPARAMS:
  PROPHET:
    COUNTRY: 'CA'
    CHANGEPOINT_PRIOR_SCALE: 0.001
    SEASONALITY_PRIOR_SCALE: 0.01
    HOLIDAYS_PRIOR_SCALE: 0.01
    SEASONALITY_MODE: 'additive'
    CHANGEPOINT_RANGE: 0.8
  ARIMA:
    UNIVARIATE: False
    AUTO_PARAMS: True
    P: 2
    D: 2
    Q: 2
  SARIMAX:
    AUTO_PARAMS: true
    TREND_P: 2
    TREND_D: 2
    TREND_Q: 2
    SEASONAL_P: 2
    SEASONAL_D: 2
    SEASONAL_Q: 2
    M: 24
  ANN: 
    UNIVARIATE: true
    T_X: 168
    BATCH_SIZE: 48
    EPOCHS: 120
    PATIENCE: 15
    VAL_FRAC: 0.15
    LR: 0.0001
    LOSS: 'mse'
    DROPOUT: 0.3
    FC0_UNITS: 160
    FC1_UNITS: 160
    FC2_UNITS: 64
    PREPROCESS: ['fragments']   # List from [('fragments' or 'windowed'), 'virtual', 'cluster', 'pca']
  LSTM:
    UNIVARIATE: true
    T_X: 168
    BATCH_SIZE: 48
    EPOCHS: 100
    PATIENCE: 15
    VAL_FRAC: 0.25
    LR: 0.0001
    LOSS: 'mse'
    UNITS: 128
    DROPOUT: 0.25
    FC0_UNITS: 128
    FC1_UNITS: 128
    PREPROCESS: ['fragments']
  GRU:
    UNIVARIATE: false
    T_X: 168
    BATCH_SIZE: 32
    EPOCHS: 100
    PATIENCE: 10
    VAL_FRAC: 0.25
    LR: 0.0001
    LOSS: 'mse'
    UNITS: 128
    DROPOUT: 0.25
    FC0_UNITS: 128
    FC1_UNITS: 128
    PREPROCESS: ['fragments']
  1DCNN:
    UNIVARIATE: true
    T_X: 180
    BATCH_SIZE: 32
    EPOCHS: 500
    PATIENCE: 5
    VAL_FRAC: 0.1
    LR: 0.0003
    LOSS: 'mae'
    FILTERS: 16
    KERNEL_SIZE: 3
    STRIDE: 1
    N_CONV_LAYERS: 2
    FC0_UNITS: 64
    FC1_UNITS: 32
    DROPOUT: 0.0
    PREPROCESS: ['fragment']
  LINEAR_REGRESSION:
    UNIVARIATE: true
    T_X: 300
  RANDOM_FOREST:
    UNIVARIATE: true
    T_X: 365
    N_ESTIMATORS: 100
    LOSS: 'mse'

HPARAM_SEARCH:
  PROPHET:
    CHANGEPOINT_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.001, 0.5]
    SEASONALITY_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.01, 10]
    HOLIDAYS_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.01, 10]
    SEASONALITY_MODE:
      TYPE: 'set'
      RANGE: ['additive', 'multiplicative']
  ANN:
    T_X:
      TYPE: 'set'
      RANGE: [168]
    BATCH_SIZE:
      TYPE: 'set'
      RANGE: [16, 24, 48]
    PATIENCE:
      TYPE: 'int_uniform'
      RANGE: [5, 15]
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    LOSS:
      TYPE: 'set'
      RANGE: ['mse']
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
    FC0_UNITS:
      TYPE: 'set'
      RANGE: [96, 160]
    FC1_UNITS:
      TYPE: 'set'
      RANGE: [64, 96, 160]
    FC2_UNITS:
      TYPE: 'set'
      RANGE: [32, 64, 96, 160]
    PREPROCESS: 
      TYPE: 'set'
      RANGE: ['fragments'] 
  LSTM:
    T_X:
      TYPE: 'int_uniform'
      RANGE: [30, 365]
    BATCH_SIZE:
      TYPE: 'set'
      RANGE: [16, 32]
    PATIENCE:
      TYPE: 'int_uniform'
      RANGE: [5, 15]
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    LOSS:
      TYPE: 'set'
      RANGE: ['mse', 'mae', 'huber_loss']
    UNITS:
      TYPE: 'set'
      RANGE: [4, 8, 16]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
    FC0_UNITS:
      TYPE: 'set'
      RANGE: [32, 64, 128]
    FC1_UNITS:
      TYPE: 'set'
      RANGE: [16, 32, 64]
  1DCNN:
    T_X:
      TYPE: 'int_uniform'
      RANGE: [30, 365]
    BATCH_SIZE:
      TYPE: 'set'
      RANGE: [16, 32, 64]
    PATIENCE:
      TYPE: 'int_uniform'
      RANGE: [5, 15]
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    LOSS:
      TYPE: 'set'
      RANGE: ['mse', 'mae', 'huber_loss']
    FILTERS:
      TYPE: 'set'
      RANGE: [4, 8, 16]
    KERNEL_SIZE:
      TYPE: 'set'
      RANGE: [3, 5]
    STRIDE:
      TYPE: 'int_uniform'
      RANGE: [1, 2]
    N_CONV_LAYERS:
      TYPE: 'int_uniform'
      RANGE: [1, 3]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
    FC0_UNITS:
      TYPE: 'set'
      RANGE: [16, 32, 64]
    FC1_UNITS:
      TYPE: 'set'
      RANGE: [8, 16, 32]
  LINEAR_REGRESSION:
    T_X:
      TYPE: 'int_uniform'
      RANGE: [30, 365]

# Data clustering
K-PROTOTYPES:
  K: 4
  N_RUNS: 15
  N_JOBS: 3
  K_MIN: 3
  K_MAX: 12
  FEATS_TO_EXCLUDE: ['RATE_CLASS', 'NOM', 'REDUC_FAC', 'SSF', 'W_HEC_AF', 'RES_LDM', 'RES_MDM', 'RES_HR']
  EVAL_DATE: '2020-09-17'
  EXPERIMENT: 'cluster_clients'               # One of {'cluster_clients', 'silhouette_analysis'}